config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "hotels#index"
  
  get 'hotels/search'
  
  resources :hotels, only:[:new, :create, :edit, :update, :show] do
    resources :reviews, only:[:index, :create, :destroy]
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  has_many :reviews
  has_one_attached :image

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:total_score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:total_score).round(1).to_f * 100 / 5
    end
  end

  with_options presence: true do
    validates :image
    validates :name
  end

  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :search_hotel, only: [:index, :search]
  def index
    @hotels = Hotel.all.page(params[:page]).per(5)
    @hotel = Hotel
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to hotel_path(@hotel)
    else
      render :new
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @review = Review.new
  end

  def search
    @hotels = @p.result
    @hotels = @hotels.page(params[:page])
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :category_id, :image)
  end

  def search_hotel
    @p = Hotel.ransack(params[:q])
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_hotel.html.erb
      <div class="card mb-6">
        <header class="card-header">
          <%= link_to edit_hotel_path(hotel) do %>
            <p class="card-header-title">
              <%= hotel.name %>
              <%= ":#{hotel.category.name}"%>   
            </p>
          <% end %>
        </header>
        <div class="card-content mb-3">
          <%= image_tag(hotel.image, class: :card__img)if hotel.image.attached? %>
          <div class="content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= hotel.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= hotel.avg_score %>点（<%= hotel.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <footer class="card-footer">
          <%= link_to hotel_reviews_path(hotel), class: "button card-footer-item" do %>
              レビューを見る
            <% end %>
            <%= link_to hotel_path(hotel), class: "button card-footer-item" do %>
              レビューを書く
            <% end %>
        </footer>
      </div>

app/views/hotels/edit.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @hotel, local: true do |f| %>
          <%= render "shared/error_messages", model: f.object %>
            <p class="form-header-text is-size-1 has-text-centered">宿泊施設を更新する<p>
          <div class="field">
            <%= f.text_field :name, class:"input", placeholder:"宿泊施設名" %>
          </div>
          <div class="field has-text-centered">
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
          </div>
          <div class="field is-size-6 has-text-centered">
          <p>
            クリックしてファイルをアップロード
            <div>
              <%= f.file_field :image, id:"hotel-image" %>
            </div>
          </p>
          </div>
          <div class="actions mt-6 has-text-centered">
            <%= f.submit "更新する" ,class:"button is-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/hotels/index.html.erb
<section class="section mt-6">
<h1 class="columns is-centered form-header-text is-size-5">
  宿泊施設検索
</h1>
<div class="form-header-text has-text-centered">
  <%= search_form_for @p, url: hotels_search_path do |f| %>
    <%= f.label :category_id_eq, 'カテゴリー検索' %>
    <%= f.collection_select :category_id_eq, Category.all,:id,:name,{class:"category-select"} %>
    <%= f.submit '検索' %>
  <% end %>
</div>
  <div class="container">  
    <div class="columns is-centered">
    <div class="column is-5">
      <p class="form-header-text is-size-4 has-text-centered">宿泊施設・カテゴリー一覧</p>
      <% @hotels.each do |hotel|%>
        <%= render partial: "hotel", locals: { hotel: hotel } %>
      <% end %>
    </div>
    </div>
    <div class="columns is-centered">
    <%= paginate(@hotels) %>
    </div>
  </div>
</section>

app/views/hotels/new.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @hotel, url:hotels_path, local: true do |f| %>

        <%= render "shared/error_messages", model: f.object %>

        <p class="form-header-text is-size-1 has-text-centered">宿泊施設を投稿する<p>
        <div class="field">
          <%= f.text_field :name, class:"input", placeholder:"宿泊施設名" %>
        </div>
        <div class="field has-text-centered">
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
        </div>
        <div class="field is-size-6 has-text-centered">
        <p>
          クリックしてファイルをアップロード(必須)
          <div>
            <%= f.file_field :image, id:"hotel-image" %>
          </div>
        </p>
        </div>
        <div class="actions mt-6 has-text-centered">
          <%= f.submit "投稿する" ,class:"button is-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<section>

app/views/hotels/search.html.erb
<section class="section mt-6">
<h1 class="columns is-centered form-header-text is-size-5">
  検索結果
</h1>

  <div class="container">  
    <div class="columns is-centered">
    <div class="column is-5">
      <p class="form-header-text is-size-4 has-text-centered">宿泊施設・カテゴリー一覧</p>
      <% @hotels.each do |hotel|%>
        <%= render partial: "hotel", locals: { hotel: hotel } %>
      <% end %>
    </div>
    </div>
  </div>
</section>

app/views/hotels/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <%= link_to edit_hotel_path(@hotel) do %>
              <p class="card-header-title">
                <%= @hotel.name %>
                <%= ":#{@hotel.category.name}"%>
              </p>
            <% end %>
          </header>
          <div class="card-content mb-3">
            <%= image_tag @hotel.image %>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @hotel.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @hotel.avg_score %>点（<%= @hotel.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <%= render 'reviews/form', review: @review, hotel: @hotel %>
      </div>
    </div>
  </div>
</section>