config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "hotels#index"
  
  get 'hotels/search'
  
  resources :hotels, only:[:new, :create, :edit, :update, :show] do
    resources :reviews, only:[:index, :create, :destroy]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  def index
    @hotel = Hotel.find(params[:hotel_id])
    @reviews = @hotel.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to hotel_reviews_path(@review.hotel)
    else
      @hotel = Hotel.find(params[:hotel_id])
      render 'hotels/show'
    end
  end

  def destroy
    @hotel = Hotel.find(params[:hotel_id])
    @review = @hotel.reviews.find(params[:id])
    @review.destroy
    if redirect_to hotel_reviews_path(@review.hotel)
    end
  end

  private

  def review_params
    params.require(:review).permit(:total_score, :comment).merge(user_id: current_user.id, hotel_id: params[:hotel_id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>
<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="rating-box mt-3">
  <%= form_with model: review, url: hotel_reviews_path(@hotel), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :hotel_id, value: @hotel.id %>
    <%= f.hidden_field :total_score, id: "rating-value" %>
    <%= f.text_field :comment, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューを見る", hotel_reviews_path(@hotel), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <p class= "form-header-text is-size-4 has-text-centered">宿泊施設レビュー</p>
        <div class="card mb-6">
          <header class="card-header">
            <%= link_to edit_hotel_path(@hotel) do %>
              <p class="card-header-title">
                <%= @hotel.name %>
                <%= ":#{@hotel.category.name}"%>
              </p>
            <% end %>
          </header>
          <div class="card-content mb-3">
            <%= image_tag @hotel.image %>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @hotel.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @hotel.avg_score %>点（<%= @hotel.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th><th></th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.name %></td>
                <td><%= review.total_score %></td>
                <td><%= review.comment %></td>
                <% if user_signed_in? && current_user.id == review.user_id %>
                  <td><%= link_to "削除", hotel_review_path(review.hotel.id, review.id), method: :delete%></td>
                <% else %>
                <td></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class=has-text-centered>
          <%= link_to "宿泊施設一覧に戻る", root_path, class: :button%>
        </div>
      </div>
    </div>
  </div>
</section>