config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "hotels#index"
  
  get 'hotels/search'
  
  resources :hotels, only:[:new, :create, :edit, :update, :show] do
    resources :reviews, only:[:index, :create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accommodation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f39db71b21.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="header">
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <p class="navbar-item">
            <%= link_to root_path do %>
              <i class="fas fa-plane-departure black"></i>
              <strong class="is-size-3" style="font-family: cursive; color: black;">accommodation review</strong>
            <% end %>
          </p>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ <%= current_user.name %> さん</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <div class="nav__right">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :button %>
                <%= link_to "新規レビュー", new_hotel_path, class: :button %>
               </div>
              <% else %>
                <div class="nav__right">
                <%= link_to "ログイン", new_user_session_path, class: :button %>
                <%= link_to "ユーザー登録", new_user_registration_path, class: :button %>
                </div>
              <% end %>
            </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>